name: iOS Workflow

on:
  push:
    branches:
      - 'release_v*'

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint with SwiftLint
        run: swiftlint

      - name: Create Tag and Release
        if: startsWith(github.ref, 'refs/heads/release_v') # Only execute for branches starting with "release_v"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use the secret here
        run: |
          TAG_NAME=$(echo "${{ github.ref }}" | sed -E 's/refs\/heads\/release_v//')
          RELEASE_NAME="Release $TAG_NAME"
          RELEASE_BODY="This is the release for version $TAG_NAME"

          echo "Creating tag and release..."
          git tag -a "$TAG_NAME" -m "$RELEASE_NAME"
          git push origin "$TAG_NAME"

          echo "Creating GitHub release..."
          gh auth login --with-token $GITHUB_TOKEN
          gh release create "$TAG_NAME" --target "release" --title "$RELEASE_NAME" --notes "$RELEASE_BODY"
          if [[ "${{ github.ref }}" == *veryimportant ]]; then
            echo "This is a very important release"
            gh release update "$TAG_NAME" --append-tag "very-important"
          fi
